# Generated by Django 4.2.4 on 2023-08-11 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Запись бронирования', 'verbose_name_plural': 'Записи бронирования'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AddField(
            model_name='book',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Бронируемая комната'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='date_finish',
            field=models.DateTimeField(verbose_name='Конец бронирования'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало бронирования'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Постоялец'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3, verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='room',
            name='count_places',
            field=models.IntegerField(default=1, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Есть бронь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
    ]
